### ISSUE TITLE
How to fix inconsistent icon sizes on different platforms?

### ISSUE THREAD

**Issue by tariksetia** [matfax/kivysome#52]
The is how it Looks on windows
<img width="777" alt="Win10" src="https://user-images.githubusercontent.com/1137658/94947109-bc27eb80-04fa-11eb-87e2-4af4efd68525.png">

An this is how it looks on Mac OS
<img width="937" alt="Mac" src="https://user-images.githubusercontent.com/1137658/94947153-ca760780-04fa-11eb-9fde-723354a12947.png">

You can see the difference in icon size. Following is the Kivy code for Icon Label only
```
Label:
            size_hint: None, None
            size: self.texture_size
            text_size: self.width, None
            halign: "left"
            valign: "middle"
            markup: True
            text: "%s "%(icon(root.get_status_icon(root.status), 32, root.get_color_for_status(root.status), 'fontawesome-FontGroup.SOLID'))
```

Is there any way to specify kivysome font size using kivy.mertics.sp or dp?
